version: '1.0'

services:

  frontend:
    image: virabshetkar/bookexchangefrontend
    container_name: bookexchangefrontend
    build: 
      context: ./frontend

  backend: 
    image: virabshetkar/bookexchangebackend
    container_name: bookexchangebackend
    build: 
      context: ./backend
    env_file:
      - backend.env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql
    container_name: bookexchangedatabase
    env_file:
      - database.env
    ports:
      - 3306
      - 33060
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  mailer:
    image: dockage/mailcatcher
    container_name: bookexchangemailer
    ports:
      - "1080:1080"
      - 1025

  nginx: 
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend